FROM docker.elastic.co/logstash/logstash:7.17.9

# Remove the default pipeline config and copy ours in
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
COPY logstash/logstash.conf /usr/share/logstash/pipeline/logstash.conf
